---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchcomponenttemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchcomponenttemplates/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchcomponenttemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchilms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchilms/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchilms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchindextemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchindextemplates/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchindextemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchslms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchslms/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchslms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchsnapshotrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchsnapshotrepositories/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchsnapshotrepositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchwatchers/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchwatchers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - licenses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - licenses/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - licenses/status
  verbs:
  - get
  - patch
  - update
