---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: operator-elk-extra
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearch.k8s.elastic.co
  resources:
  - elasticsearches
  verbs:
  - get
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchcomponenttemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchcomponenttemplates/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchcomponenttemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchilms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchilms/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchilms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchindextemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchindextemplates/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchindextemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchroles/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchroles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchslms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchslms/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchslms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchsnapshotrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchsnapshotrepositories/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchsnapshotrepositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchwatchers/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchwatchers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - licenses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - licenses/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - licenses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - rolemappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - rolemappings/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - rolemappings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
