## Append samples you want in your CSV to this file as resources ##
resources:
- elk_v1alpha1_license.yaml
- elk_v1alpha1_elasticsearchilm.yaml
- elk_v1alpha1_elasticsearchslm.yaml
- elk_v1alpha1_elasticsearchindextemplate.yaml
- elk_v1alpha1_elasticsearchcomponenttemplate.yaml
- elk_v1alpha1_elasticsearchsnapshotrepository.yaml
- elk_v1alpha1_elasticsearchwatcher.yaml
- elk_v1alpha1_elasticsearchrole.yaml
- elk_v1alpha1_rolemapping.yaml
- elk_v1alpha1_user.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
